repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.yaml
          )$
      args:
        - --quiet-level=2
