exclude: "docs/javascripts/mathjax.js"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-added-large-files
      files: \.(json)$

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
    - id: prettier
      files: \.(json)$

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
    - id: codespell
      exclude: >
          (?x)^(
              .*\.yaml
          )$
      args:
        - --quiet-level=2
