name: GSoC Project Proposal
description: Use this template for GSoC project proposals.
title: "[GSoC Project Proposal]: "
labels: ["GSoC26", "project idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in contributing to IOOS' GSoC application this year!  
        Please complete this form to begin the process of adding a project idea to the ideas list we'll submit to Google as part of our application.  Project ideas can be edited/updated until the application period begins in March.  We will contact you with questions and feedback about your idea prior to the early February deadline to submit our Org application.
  - type: markdown
    attributes:
      value: "## Project Description"
  - type: markdown
    attributes:
      value: |
        **(Required)** Provide a concise descripion of your project idea & expected outcomes.  
        It's recommended to keep both sections under **five sentences.**  Further detail can be provided to applicants as they contact you during the application phase.  Longer project descriptions can be counterproductive with the growing use of AI."
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: Brief summary of the proposed project - what the goals of the project area/what the applicant is expected to accomplish during the GSoC coding period.  **(5 sentences maximum)**
    validations:
      required: true  
  - type: textarea
    id: outcomes
    attributes:
      label: Expected Outcomes
      description: What do you expect to get out of the project when completed?  How is this expected to improve the software, tool, or package?  **(5 sentences maximum)**
    validations:
      required: true
  - type: input
    id: skills
    attributes:
      label: Skills Required
      description: What types of skills should the applicant have to complete this project?  Short list of programing languages, software packages, or any other specific technical or general skills they should have to have a good chance of completing the project successfully.  
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Expected Project Size
      description: GSoC projects can be one of three different sizes depending on how much time you anticipate it should take to complete.  The project size limits the number of work hours the contributor will be compensated for for the project. Applicants may suggest a different project size as part of their application - this should be negotiated with them during the application period.  The value you enter here represents your expectation/guidance for applicants interested in the project.
      options: 
        - 90 hours
        - 175 hours
        - 350 hours
    validations:
      required: true
  - type: markdown
    attributes:
      value: Project duration: 90 hour projects are typically completed over a two month period, while 175 and 350 hour projects typically span the entire summer coding period. 
  - type: dropdown
    id: difficulty
    attributes:
      label: Project Difficulty
      description: Specify the difficulty of the project/experience level of potential applicants (Novice, Intermediate, Expert).
      options: 
        - Novice
        - Intermediate
        - Expert
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Mentor Information"
  - type: markdown
    attributes:
      value: **(Required)** Provide contact information for yourself and any other mentors that will particpate in your project below."
  - type: input
    id: mentors-names
    attributes:
      label: Mentor Name(s)
      description: Include mentor names as comma separated list
      placeholder: Mentor #1 Name, Mentor #2 Name, ...
    validations:
      required: true
  - type: input
    id: mentor-handles
    attributes:
      label: Mentor GitHub Handle(s)
      description: Include mentor GitHub handles as comma separated list (in the same order as mentor names)
      placeholder: e.g. @mentorgithubhandle1, @mentorgithubhandle2, ...
    validations:
      required: true
  - type: input
    id: mentor-emails
    attributes:
      label: Mentor Contact Email(s)
      description: Include mentor email addresses as a comma-separated list (in the same order as mentor names).  There should be a minimum of one email address applicants can contact with questions or to discuss their project proposal/ideas privately if they choose.
      placeholder: mentoremail1@organization.org, mentoremail2@secondaryorg.org, ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Contributor Section"
  - type: markdown
    attributes:
      value: | 
        Optional, but highly encouraged to add a Contributor Evaluation prior to the application period in Feb - March.
        Including a contributor evaluation question or coding challenge helps applicants gauge their abilities against your expectations as a mentor provides a means for you to evaluate their skills and coding abilities separate from the written application.  Assessing applicants based on GSoC project propsals alone can lead to a mismatch beween mentor expectations and contributor proficiency/suitability, from our experience.
        Expect interested applicants to follow any links you provide during the application period and be prepared to field PRs as well as comments and questions about what is included here.
  - type: textarea
    id: contributor-evaluation
    attributes:
      label: Contributor Evaluation/GSoC GitHub Issue Links  
      description: (Optional) In this section, include either 1) a link to or description of a coding-related challenge you want all applicants to complete as part of their application or 2) links to existing GitHub issues in your project's repository(s) that are labeled 'GSoC first issue' or similar that applicants can resolve to demonstrate proficiency with your project/code base.  
    validations:
      required: false
  - type: textarea
    id: additional-background
    attributes:
      label: Additional Project Background/Links   
      description: (Optional) Include a list of links to your project code repositories or any other references that are relevant to your project idea.
    validations:
      required: false
  - type: input
    id: previous-projects
    attributes:
      label: Previous Project Idea Link(s)
      description: (Optional) If you're re-submitting a project idea from a previous year, include the link the original GitHub issues here. 
      placeholder: e.g. https://github.com/ioos/gsoc/issues/93
    validations:
      required: false
