name: GSoC Project Proposal
description: Use this template for GSoC project proposals.
title: "[GSoC Project Proposal]: "
labels: ["GSoC25", "project idea"]
body:
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: Summary of the proposed project - what the applicant is expected to accomplish during the GSoC coding period.  Include any background materials such as links to any existing code, documentation including references, graphics/diagrams, or any other materials that are helpful in explaining the project to applicants.  Provide as much detail as possible for your description, keeping in mind that you can add more later by editing the resulting GitHub issue directly.  **(5 sentences for initial project descriptions, with the more detail the better added prior to the Org application deadline in ~ early Feb)**  
    validations:
      required: true  
  - type: textarea
    id: outcomes
    attributes:
      label: Expected Outcomes
      description: What do you expect to get out of the project when completed?  How is this expected to improve the software, tool, or package?  **(2 - 5 sentences)**
    validations:
      required: true
  - type: input
    id: skills
    attributes:
      label: Skills Required
      description: What types of skills does the applicant need to complete this project?  List of programing languages, software packages, or any other specific skills they should have to have a good chance of success.  
    validations:
      required: true
  - type: textarea
    id: additional-background
    attributes:
      label: Additional Background/Issues   
      description: Include links to any existing issues in your code repositor(ies) that give context for the project or that might be used to evaluate an applicant's suitability for the proposed project.  Issues can also be created specifically to test applicants' relevant skills during the GSoC contributor application period.  Expect interested applicants to follow any links you provide during the application period and be prepared to field PRs as well as comments and questions about what is included here.  
    validations:
      required: false
  - type: input
    id: mentors
    attributes:
      label: Mentor(s)
      description: Include mentor names and GitHub handles as comma separated list
      placeholder: Mentor Name (@somegithubhandlethatsurelynoonealreadyhas), Mentor Name 2 (@someothergithubhandlethatsurelynoonealreadyhas)
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Expected Project Size
      description: GSoC projects can be one of three different sizes depending on your estimation of the amount of time it should take the student to complete.  Keep in mind that the project size will be the maximum number of hours the contributor will be compensated for for the project, and also will impact the amount of time you during the coding period you commit to mentor for, generally.  If uncertain, select a larger size.  The student can also suggest a different size as part of their application.  
      options: 
        - 90 hours
        - 175 hours
        - 350 hours
    validations:
      required: true
  - type: dropdown
    id: difficulty
    attributes:
      label: Project Difficulty
      description: Specify the expected difficulty of the project (Novice, Intermediate, Expert).
      options: 
        - Novice
        - Intermediate
        - Expert
    validations:
      required: false
