name: GSoC Project Proposal
description: Use this template for GSoC project proposals.
title: "[GSoC Project Proposal]: "
labels: ["GSoC26", "project idea"]
body:
  - type: markdown
    attributes:
      value: "### Project Description/Outcomes |
      (Required) Provide a concise descripion of your project idea & expected outcomes.  It's recommended to keep both sections under five sentences.  Further detail can be provided to applicants as they contact you during the application phase.  Longer descriptions can be counterproductive with the growing use of AI."
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: Summary of the proposed project - what the applicant is expected to accomplish during the GSoC coding period.  Include any background materials such as links to any existing code, documentation including references, graphics/diagrams, or any other materials that are helpful in explaining the project to applicants.  Provide as much detail as possible for your description, keeping in mind that you can add more later by editing the resulting GitHub issue directly.  **(5 sentences for initial project descriptions, with the more detail the better added prior to the Org application deadline in ~ early Feb)**  
    validations:
      required: true  
  - type: textarea
    id: outcomes
    attributes:
      label: Expected Outcomes
      description: What do you expect to get out of the project when completed?  How is this expected to improve the software, tool, or package?  **(2 - 5 sentences)**
    validations:
      required: true
  - type: input
    id: skills
    attributes:
      label: Skills Required
      description: What types of skills does the applicant need to complete this project?  Short list of programing languages, software packages, or any other specific skills they should have to have a good chance of success.  
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Expected Project Size
      description: GSoC projects can be one of three different sizes depending on your estimation of the amount of time it should take the student to complete.  Keep in mind that the project size will be the maximum number of hours the contributor will be compensated for for the project, and also will impact the amount of time you during the coding period you commit to mentor for, generally.  If uncertain, select a larger size.  The student can also suggest a different size as part of their application.  
      options: 
        - 90 hours
        - 175 hours
        - 350 hours
    validations:
      required: true
  - type: dropdown
    id: difficulty
    attributes:
      label: Project Difficulty
      description: Specify the expected difficulty of the project (Novice, Intermediate, Expert).
      options: 
        - Novice
        - Intermediate
        - Expert
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "### Mentor Information |
      (Required) Provide contact information for yourself and any other mentors that will particpate in your project below."
  - type: input
    id: mentors-names
    attributes:
      label: Mentor Name(s)
      description: Include mentor names as comma separated list
      placeholder: Mentor #1 Name, Mentor #2 Name, ...
    validations:
      required: true
  - type: input
    id: mentor-handles
    attributes:
      label: Mentor GitHub Handle(s)
      description: Include mentor GitHub handles as comma separated list (in the same order as mentor names)
      placeholder: e.g. @ioosmentorgithubhandle1, @ioosmentorgithubhandle2, ...
    validations:
      required: true
  - type: input
    id: mentor-emails
    attributes:
      label: Mentor Contact Email(s)
      description: Include mentor email addresses as a comma-separated list (in the same order as mentor names).  There should be a minimum of one email address applicants can contact with questions or to discuss their project proposal/ideas privately if they choose.
      placeholder: ioosgsocmentoremail1@organization.org, ioosgsocmentoremail2@secondaryorg.org, ...
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "### Contributor Section | 
      Optional, but highly encouraged that you fill in the sections below to help applicants understand your project and to provide some means to evaluation their skills and coding abilities separate from the application."
  - type: markdown
    attributes:
      value: Optional, but highly encouraged that you fill in the sections below to help applicants understand your project and to provide some means to evaluation their skills and coding abilities separate from the application.
  - type: textarea
    id: contributor-evaluation
    attributes:
      label: Contributor Evaluation/GSoC GitHub Issue Links  
      description: We strongly encourage mentors to provide a way to evaluate applicants' knowledge, skills, and abilities as part of the application process.  Assessing applicants based on GSoC project propsals alone can lead to a mismatch beween mentor expectations and contributor proficiency/suitability from our experience.  In this section, optionally include either 1) a link to or description of a coding-related challenge you want all applicants to complete as part of their application or 2) links to existing GitHub issues in your project's repository(s) that are labeled 'GSoC first issue' or similar that applicants can resolve to demonstrate proficiency with your project/code base.  Expect interested applicants to follow any links you provide during the application period and be prepared to field PRs as well as comments and questions about what is included here.  
    validations:
      required: false
  - type: textarea
    id: additional-background
    attributes:
      label: Additional Project Background/Links   
      description: Include a list of links to your project code repositories or any other references that are relevant to your project idea, if not included in the Project Description or elsewhere.  Any prior GSoC completed project that pertains to this project idea might be included here.
    validations:
      required: false
  - type: input
    id: previous-projects
    attributes:
      label: Previous Project Idea Link(s)
      description: If you're re-submitting a project idea from a previous year, include links to the closed GitHub issues here.  This helps applicants understand any previous communication about the project idea that has taken place. 
      placeholder: e.g. https://github.com/ioos/gsoc/issues/93
    validations:
      required: false
